name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install GCC 11
      run: |
        sudo apt install g++-11
        sudo update-alternatives --install /usr/bin/g++-11 11
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make check
      run: make check
